### ISSUE TITLE
Error on POST to /Autodiscover/Autodiscover.xml

### ISSUE THREAD

**Issue by denogio** [Tiliq/autodiscover.xml#1]
Hi
I have tried your app, and it works with autoconfig, but with autodiscover i get the following error when i POST to /Autodiscover/Autodiscover.xml
I have tried nodejs version 4, 5, 6 and 7.. All gives the same error..

TypeError: Cannot read property 'root' of undefined
      at Object.autodiscover (/tmp/autodiscover.xml/index.js:22:56)
      at next (native)
      at Object.dispatch (/tmp/autodiscover.xml/node_modules/koa-router/lib/router.js:335:14)
      at next (native)
      at onFulfilled (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:65:19)
      at /tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:54:5
      at Object.co (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:69:7)

**Comment by kevinmartin** [comment]
Can you `console.log(this.request.body)` at the top of that function and post the output here?

Context will allow us to help you out better.

**Comment by denogio** [comment]
TypeError: Cannot read property 'root' of undefined
      at Object.autodiscover (/tmp/autodiscover.xml/index.js:23:56)
      at next (native)
      at Object.dispatch (/tmp/autodiscover.xml/node_modules/koa-router/lib/router.js:335:14)
      at next (native)
      at onFulfilled (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:65:19)
      at /tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:54:5
      at Object.co (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/tmp/autodiscover.xml/node_modules/koa/node_modules/co/index.js:69:7)

{ declaration: { attributes: { version: '1.0' } },
  root: 
   { name: 'Autodiscover',
     attributes: 
      { 'xmlns:xsd': 'http://www.w3.org/2001/XMLSchema',
        'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
        xmlns: 'http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006' },
     children: [ [Object] ],
     content: '' } }

**Comment by kevinmartin** [comment]
The error is saying that `this.request.body` is undefined, but it's outputing an object...

I can't seem to replicate this issue on my end. If you can figure it out, let us know.

**Comment by denogio** [comment]
How are you deploying?

All i have done is 
```
git clone 
npm init
node index.js
```
And then i use apache as a proxy in front..

**Comment by kevinmartin** [comment]
We deploy using Heroku, per the instructions in the README.

Btw, seems to be a typo, but make sure you `npm install` instead of `npm init`.

You might want to try to add some extra debugging around those lines and see what's coming in. It just doesn't make sense why you have data, but it's saying it's undefined.

**Comment by denogio** [comment]
Just tried to deploy to heroku.. but im also the same error there..

**Comment by sparse91** [comment]
I get same error with both Apache and Nginx.
node v12.18.4
